fix: composer missing

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -17,6 +17,13 @@ runs:
   using: "composite"
   steps:
     - run: |
+        # Install Docker Compose if not present
+        if ! command -v docker-compose &> /dev/null; then
+          echo "Docker Compose not found. Installing..."
+          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+          sudo chmod +x /usr/local/bin/docker-compose
+        fi
+
         #!/bin/bash
         set -e
 
